### ISSUE TITLE
Submissions of Completed Challenges doesn't appear

### ISSUE THREAD

**Issue by 3amrSaad** [appirio-tech/tc-site#312] opened 2016-07-22 16:59 UTC
### Steps to Reproduce
1. Open Safari
2. Go to "https://www.topcoder-dev.com/challenge-details/30049240/?type=design#winner" and click on the Submissions tab
3. Go to "https://members.topcoder-dev.com/challenge-details/30049240/?type=design#winner" and click on the Submissions tab, Observe

### Expected Result(s)
Submissions of the Challenge should be displayed.

### Actual Result
An empty space instead, Nothing appears.

### Environment
**Operating System:** MAC OS X (Mavericks), Version 10.9
**Browser:** Safari Version 7.0 (9537.71)
### Screenshots
See comments section.

**Comment by 3amrSaad** [comment] 2016-07-22 17:02
http://icecream.me/bb626d801259bda4a0852ccc2ad3b97c

http://icecream.me/112a8fa4641ec15f3134a714d5a74d03

**Comment by tladendo** [comment] 2016-07-25 13:00
duplicate of #296

**Closed by tladendo** 2016-07-25 13:00 UTC
