### ISSUE TITLE
Final review tool tip showing over Approval

### ISSUE THREAD

**Issue by kaygee1** [appirio-tech/tc-site#298] opened 2016-07-22 15:45 UTC
Open pages
https://www.topcoder-dev.com/challenge-details/30049604/?type=develop

https://members.topcoder-dev.com/challenge-details/30049604/?type=develop

See the second box on the right side
CLick on ? on Final Review and observe where it opens up

in topcoder-dev.com  it appears over Approval header

in members.topcoder-dev it appears over Final REview itself

Windows 10 Chrome 51

![5](https://cloud.githubusercontent.com/assets/5115050/17062617/5a5cf5ce-5051-11e6-837d-b915d2295082.png)

![6](https://cloud.githubusercontent.com/assets/5115050/17062627/5f013496-5051-11e6-85c3-9073562e2e8d.png)

**Comment by tladendo** [comment] 2016-07-25 12:41
possibly a duplicate of #295

**Closed** 2016-07-28 14:25 UTC
Labels: question
