### ISSUE TITLE
Approval tool tip text window opens over Challenge links header

### ISSUE THREAD

**Issue by kaygee1** [appirio-tech/tc-site#299] opened 2016-07-22 15:49 UTC
Open pages
https://www.topcoder-dev.com/challenge-details/30049604/?type=develop

https://members.topcoder-dev.com/challenge-details/30049604/?type=develop

See the second box on the right side
CLick on ? on Aprroval and observe where it opens up

in topcoder-dev.com it appears over Challenge Links header

in members.topcoder-dev it appears over Approval  itself

Windows 10 Chrome 51

![7](https://cloud.githubusercontent.com/assets/5115050/17062768/f09c39fa-5051-11e6-96ae-5c288f05e375.png)

![8](https://cloud.githubusercontent.com/assets/5115050/17062771/f45cd0fe-5051-11e6-912f-4ec4408d9edf.png)

**Comment by tladendo** [comment] 2016-07-25 12:43
duplicate of #298

**Closed by tladendo** 2016-07-25 12:43 UTC
Labels: duplicate
