### ISSUE TITLE
XMLHttpRequest Access-Control-Allow-Origin header config error: contains multiple values

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/tc-site#271] opened 2016-07-22 14:35 UTC
Access-Control-Allow-Origin is misconfigured on the server and contains multiple values, resulting in an error in console.

Browser: Chrome 51 on Windows 10

**Steps:**
- Visit test website in Chrome
- Open chrome inspector and switch to console
- see error

**Expected:**
- No Access-Control-Allow-Origin XMLHttpRequest errors

**Actual:**
- Error from misconfigured server values.

**Screenshot:**
http://i.imgur.com/0Hppags.png

**Comment by tladendo** [comment] 2016-07-25 12:13
couldn't reproduce and this page is out of scope anyway

**Closed by tladendo** 2016-07-25 12:13 UTC
