### ISSUE TITLE
[Challenges] Clicking on Browser back button won't load the platform and Technology drop downs

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/tc-site#323] opened 2016-07-23 12:29 UTC
Description
-----------------------------------------------------------------
[Challenges] Clicking on Browser back button won't load the platform and Technology drop downs

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://members.topcoder-dev.com)
- Login as a valid user
- In the 'challenges' page
- Go to Grid View
- Go to SOFTWARE DEVELOPMENT CHALLENGES
- Click 'Past Challenges'
- Click on 'Android' from the Challenge tags
- Then Filter the Data from 'JavaScript'
- You can see few challenges 
- Click on this challenge
- Click Browser back button
- Check the challenge listing page
- Won't load the platform and Technology drop downs in Sub-Domain

Expected Result(s)
-----------------------------------------------------------------
- Must load the platform and Technology drop downs

Actual Result
-----------------------------------------------------------------
- Clicking on Browser back button won't load the platform and Technology drop downs

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 52.0.2743.82 m, FF 47.0.1, IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![9-full domain](https://cloud.githubusercontent.com/assets/4592712/17077878/329d12fe-50ff-11e6-84fa-7c757cc05fe3.png)
![9-sub domain](https://cloud.githubusercontent.com/assets/4592712/17077879/32cd7926-50ff-11e6-85c7-2358823cc430.png)

**Comment by tladendo** [comment] 2016-07-25 13:14
duplicate of #320

**Closed by tladendo** 2016-07-25 13:14 UTC
Labels: try-windows
