### ISSUE TITLE
Winners of completed challenges doesn't appear

### ISSUE THREAD

**Issue by 3amrSaad** [appirio-tech/tc-site#311] opened 2016-07-22 16:52 UTC
### Steps to Reproduce
1. Open Safari
2. Go to "https://www.topcoder-dev.com/challenge-details/30049240/?type=design#winner"
3. Go to "https://members.topcoder-dev.com/challenge-details/30049240/?type=design#winner" and Observe

### Expected Result(s)
Winners of this completed challenge should appear.

### Actual Result
An empty space instead, Nothing is displayed.

### Environment
**Operating System:** MAC OS X (Mavericks), Version 10.9
**Browser:** Safari Version 7.0 (9537.71)
### Screenshots
See comments section.

**Comment by 3amrSaad** [comment] 2016-07-22 16:54
http://icecream.me/cca1cd359e614e0ebde96b4e9982b2a1

http://icecream.me/48ef94f4bd3216f09481afa32272b826

**Comment by tladendo** [comment] 2016-07-25 12:57
duplicate of #296

**Closed by tladendo** 2016-07-25 12:57 UTC
