### ISSUE TITLE
challenges not loading while soring winners 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/tc-site#307] opened 2016-07-22 16:09 UTC
Steps to reproduce
-------------
     Goto  https://members.topcoder-dev.com/challenges/develop/past/?pageIndex=1
    Goto  https://www.topcoder-dev.com/challenges/develop/past/?pageIndex=1
    Both Click Winners 
    see 

Expected results
-------------
    must load challenges 
Current results
-------------------
    challenges  not loading properly 
![Uploading 2016-07-22_2135.png…]()
![2016-07-22_2136](https://cloud.githubusercontent.com/assets/3225433/17063402/b5a4abfe-5054-11e6-85c1-cada4b22c21c.png)

Environment
-------------------
    Browser:  FF 47.0.1
    Operating System: Windows 8.1

**Comment by karthikbecse** [comment] 2016-07-22 16:18
![2016-07-22_2135](https://cloud.githubusercontent.com/assets/3225433/17063509/47b5b51a-5055-11e6-9a83-c8d1da73ef99.png)

**Comment by tladendo** [comment] 2016-07-25 12:53
duplicate of #296

**Closed by tladendo** 2016-07-25 12:53 UTC
