### ISSUE TITLE
Difference in Check point awards display

### ISSUE THREAD

**Issue by kaygee1** [appirio-tech/tc-site#317] opened 2016-07-22 17:52 UTC
Open pages 

https://members.topcoder-dev.com/challenge-details/30048752/?type=design

https://www.topcoder-dev.com/challenge-details/30048752/?type=design

See the check point prize

actual - topcoder-dev- it says 5 CHECKPOINT AWARDS WORTH $100 EACH

in members.topcoder-dev - it says NO CHECKPOINT AWARDS

expected- both to be the same

![11](https://cloud.githubusercontent.com/assets/5115050/17066085/080bf218-5063-11e6-9a76-71fba76ff0e0.png)

![12](https://cloud.githubusercontent.com/assets/5115050/17066089/0b3abf46-5063-11e6-836b-1481363108a4.png)

**Comment by tladendo** [comment] 2016-07-25 13:03
duplicate of #315

**Closed by tladendo** 2016-07-25 13:03 UTC
