### ISSUE TITLE
Missing content on design challenge details > submissions tab

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/tc-site#306] opened 2016-07-22 16:05 UTC
On a challenges details page for design competitions, clicking on the submissions tab leads to a contentless page, whereas the non-members page has the missing message "This challenge has not completed yet, submissions are viewable only for completed challenges." for same challenge.

Browser: Chrome 51 on Windows 10

**Steps:**
- Visit https://members.topcoder-dev.com/challenge-details/30050393/?type=design
- Click submissions(1) tab
- Tab is blank with no content or messages.

**Expected:**
- similar message should be displayed on members subdomain as old domain: "This challenge has not completed yet, submissions are viewable only for completed challenges."

**Actual:**
- tab is missing page contents.

**Screenshot:**
http://imgur.com/b6aqmVU.png

**Comment by tladendo** [comment] 2016-07-25 12:51
duplicate of #296

**Closed by tladendo** 2016-07-25 12:51 UTC
